config/routes.rb
Rails.application.routes.draw do
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :impressions

  ###########
  # admin routes
  ###########
  namespace :admin do
    resources :business_categories
    
    resources :businesses do
      resources :gallery_photos, only: [ :new, :create]
      member do
        patch :ban
        patch :verify
        patch :change_featured_status
        get :invite_page_admin
        post :send_admin_invitation
        get :request_ownership_transfer
        patch :transfer_ownership
      end
    end
    resources :admins do
      member do
        patch :activate_deactivate
        patch :reset_password
      end
    end
    resources :users, only: [:index, :show] do
      member do
        patch :ban
      end
    end
    resources :slider_images
    resources :artists do
      resources :gallery_photos, only: [ :new, :create]
      member do
        patch :change_status
        patch :change_featured_status
        patch :verify
        get :invite_page_admin
        post :send_admin_invitation
        get :request_ownership_transfer
        patch :transfer_ownership
      end
    end
    resources :awards, :events, :gallery_photos, :life_events, :news_stories, :collection_albums, :blogs, :songs, :books, :photo_arts, :productions, :suggested_updates, except: [:new, :delete] do
      member do
        patch :change_status
        patch :ban
      end
    end

    resources :events do
      member do
        patch :change_featured_status
      end
    end
    resources :sites

    resources :site_ads
    get 'dashboard' => 'pages#dashboard'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    root 'sessions#new'
  end

  resources :users, shallow: :true do
    resources :artists, only: [:new, :create]
    resources :businesses, only: [:new, :create]
    member do
      get :confirm_email
      get :dashboard
      get :accept_admin_invitation
      get :confirm_email
      get 'edit_profile_pic' => 'users#edit_profile_pic'
      get 'fanned_artists'
      get 'liked_businesses'
      get 'entity_management'
    end
  end

  #sign_up routes
  get 'signup' => 'users#new'

  # Sessions routes
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroyuser'

  get 'load_specialities' => 'artists#load_specialities'
  get 'terms_and_conditions' => 'pages#terms_and_conditions'
  get 'privacy' => 'pages#privacy'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # autocomplete routes
  get 'autocomplete_director_name' => 'productions#get_directors'
  get 'autocomplete_production_company_name' => 'productions#get_production_companies'
  get 'autocomplete_production_language' => 'productions#get_production_languages'
  get 'autocomplete_publishing_company_name' => 'books#get_publishing_companies'
  get 'autocomplete_event_venues' => 'events#get_venues'

  get 'autocomplete_nominee/:award_category_id' => 'nominees#get_nominee', as: :autocomplete_nominee

  get 'search' => 'search#get_results', as: :search
  get 'music_artist_listings' => 'artists#music_artist_listings', as: :music_artist_listings
  get 'photo_art_artist_listings' => 'artists#photo_art_artist_listings', as: :photo_art_artist_listings
  get 'fashion_artist_listings' => 'artists#fashion_artist_listings', as: :fashion_artist_listings
  get 'literature_artist_listings' => 'artists#literature_artist_listings', as: :literature_artist_listings
  get 'production_artist_listings' => 'artists#production_artist_listings', as: :production_artist_listings

  get 'artist_listings' => 'artists#artist_listings', as: :artist_listings
  get 'business_listings' => 'businesses#business_listings', as: :business_listings
  get 'item_listings' => 'search#item_listings', as: :item_listings
  get 'media_listings' => 'media#media_listings', as: :media_listings
  get 'awards_listings' => 'awards#awards_listings', as: :awards_listings

  get 'music' => 'songs#music_dashboard', as: :music_dashboard
  get 'arts' => 'photo_arts#photo_arts_dashboard', as: :photo_arts_dashboard
  get 'fashion' => 'artists#fashion_dashboard', as: :fashion_dashboard
  get 'literature' => 'books#literature_dashboard', as: :literature_dashboard
  get 'film' => 'productions#productions_dashboard', as: :productions_dashboard
  get 'business' => 'businesses#businesses_dashboard', as: :businesses_dashboard
  get 'events' => 'events#events_dashboard', as: :events_dashboard
  get 'media' => 'media#media_dashboard', as: :media_dashboard
  get 'awards' => 'awards#awards_dashboard', as: :awards_dashboard
  get 'deletephoto/:id' => 'gallery_photos#destroy'
  get "presskit" => 'artists#presskit', as: :presskit
  get "deactivate/:id" => 'users#ban', as: :deactivate

  root 'pages#homepage'

  resources :artists, path: "" do
    member do
      get 'add_remove_fan'
    end
  end

  resources :businesses, path: "/business" do
    member do
      get 'add_remove_fan'
    end
  end

  resources :artists, :businesses, shallow: :true do
    collection do
      get :token_inputs
    end
      resources :events, :life_events, :news_stories, :blogs, only: [:new, :create],  shallow: :true do
      resources :gallery_photos
    end

    resources :songs, only: [:new, :create]
    resources :books, only: [:new, :create]
    resources :photo_arts, only: [:new, :create]
    resources :productions, only: [:new, :create]
    resources :links
    resources :collection_albums
    resources :suggested_updates
    member do
      get :invite_page_admin
      post :send_admin_invitation
      get :request_ownership_transfer
      patch :transfer_ownership
      get :contacts
      get :book_token_inputs
      get :production_token_inputs
      get :song_token_inputs
      get :photo_art_token_inputs
      get :award_token_inputs
      get :collection_album_token_inputs
    end
  end

  resources :awards, shallow: :true do
    collection do
      get :token_inputs
    end
  end

  resources :businesses, shallow: :true do
    member do
      get 'add_remove_fan'
    end
    resources :artists
    resources :awards, shallow: :true do
    resources :gallery_photos
      member do
        get :show_awards_categories
        resources :award_categories, shallow: :true do
          member do
            resources :nominees
          end
        end
      end
    end
  end

  resources :events, :gallery_photos, :life_events, :news_stories, :blogs, :songs, :books, :photo_arts, :productions do
    member do
      get :publish
    end
    collection do
      get :token_inputs
    end
    get :publish
  end

  #this is for adding entities
  resources :artists do
    member do
      get :new_link
      post :create_link
      get :new_life_event
      post :create_life_event
      get :new_entity
      post :create_entity
      get :new_news_event_blog
      post :create_news_event_blog
      get :create_news_event_blog
      get :publish
    end
    get :publish
    resources :gallery_photos, only: [:new, :create]
  end

  resources :businesses do
    member do
      get :new_news_event_blog
      post :create_news_event_blog
      get :new_link
      post :create_link
      get :new_entity
      post :create_entity
    end
    resources :gallery_photos, only: [:new, :create]
  end
  #########

  resources :password_resets

  #omniauth routing
  get '/auth/:provider/callback', to: 'sessions#omniauth_create', as: 'omniauth_create'

  match '*a', :to => redirect('/'), via: [:get, :post]
end

app/controllers/admin/businesses_controller.rb
class Admin::BusinessesController < Admin::AdminController
  before_action :set_business, only: [:show, :edit, :update, :ban, :destroy, :verify,
    :change_featured_status, :invite_page_admin, :send_admin_invitation,
    :request_ownership_transfer, :transfer_ownership]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = if current_admin.content_administrator?
      current_admin.industries.collect{|industry| industry.businesses}.flatten!.uniq
    else
      Business.all
    end
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
    @news_events_blogs = @business.news_stories + @business.events  + @business.blogs
  end

  # GET /businesses/new
  def new
    @business = current_admin.businesses.build
  end

  # GET /businesses/1/edit
  def edit
  end

  def create_entity
    @entity = if params.has_key? :book
      @business.books.build(book_params)
    elsif params.has_key? :song
      @business.songs.build(song_params)
    elsif params.has_key? :photo_art
      @business.photo_arts.build(photo_art_params)
    elsif params.has_key? :production
      @business.productions.build(production_params)
    elsif params.has_key? :collection_album
      @business.collection_albums.build(collection_album_params)
    end

    if @entity.save
      add_gallery_photos(@entity, params[:images]) if params[:images]
      render :update_entities
    else
      render partial: 'shared/errors', locals: {entity: @entity }
    end
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = current_admin.businesses.build(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to admin_business_url(@business), notice: 'Business was successfully created.' }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to admin_business_url(@business), notice: 'Business was successfully updated.' }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def ban
    @business.toggle!(:banned)
    redirect_to admin_business_path(@business)
  end

  def verify
    respond_to do |format|
      if @business.toggle!(:verified)
        format.html { redirect_to admin_businesses_path(@business),notice: 'Business was successfully verified.' }
      else
        format.html { redirect_to admin_businesses_path(@business),notice: 'Business was not verified.' }
      end
    end
  end

  def change_featured_status
    @business.toggle!(:featured)
    @businesses = Business.all
    respond_to do |format|
      format.html { redirect_to admin_business_path(@business), notice: 'Business was successfully changed.' }
      format.js
    end
  end

  def send_admin_invitation
    if params[:invitation][:email_address].blank?
      flash[:error] = 'Please enter an email address'
      redirect_to admin_business_path(@business) and return
    end

    @user = User.find_by_email params[:invitation][:email_address]
    if @user.nil?
      @user = User.new(email: params[:invitation][:email_address])
      @user.save!(validate: false)
    end

    respond_to do |format|
      if @user.is_page_admin?(@business)
        @user.send_admin_invitation(@business)
        format.html { redirect_to admin_business_path(@business), notice: 'The user selected is already an admin' }
        format.json { render :show, status: :ok, location: @business }
      elsif @user.add_as_page_admin(@business)
        format.html { redirect_to admin_business_path(@business), notice: 'A new admin was successfully invited' }
        format.json { render :show, status: :ok, location: @business }
      end
    end
  end

  def transfer_ownership
    if params[:transfer_ownership][:new_owner].blank?
      flash[:error] = 'Please select a valid selection'
      redirect_to admin_business_path(@business) and return
    end

    @new_owner = User.find(params[:transfer_ownership][:new_owner])
    old_owner = @business.parent
    @business.parent = @new_owner
    respond_to do |format|
      if @business.save
        old_owner.add_as_page_admin(@business)
        format.html { redirect_to admin_business_path(@business), notice: "Ownership has been transferred to #{@new_owner.name}." }
        format.json { head :no_content }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to admin_businesses_url, notice: 'Business was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :logo, :retained_logo, :country, :latitude,
      :longitude, :business_category_id, :company_info, :verified, :physical_location, :phone_number,
      :email, :working_hours, industry_ids: [])
    end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
  def business_image(business)
    business.logo_stored? ? business.logo.url : 'default-business-pic.png'
  end

  def business_fan_link(business)
    business.business_fans.reload
    if business.business_fans.collect{|bf| bf.user}.include?(current_user)
      return link_to '<i class="fa fa-remove" aria-hidden="true"></i> Unfollow Business'.html_safe, add_remove_fan_business_path(business),
        remote: true, data: { confirm: "Are you sure you want to stop following #{business.name}" }
    else
      return link_to '<i class="fa fa-plus" aria-hidden="true"></i> Follow Business'.html_safe, add_remove_fan_business_path(business), remote: true
    end
  end

  def business_speciality_count(industry, locale)
    if locale == 'local' && current_user
      industry.businesses.viewable.where(country: current_user.country).count
    else
      industry.businesses.count
    end
  end
end

app/views/businesses/_alphabar-remote.html.slim
ul.list-inline
  -('a'..'z').to_a.each do |letter|
    li
      h5.text-uppercase=link_to letter, business_listings_path({industry: @industry, search_letter: letter, locale: @locale }), remote: true, class: letter == @search_letter ? 'active-link':''
  li
    h5.text-uppercase=link_to "all", business_listings_path({industry: @industry, locale: @locale }), remote: true, class: @search_letter.blank? ? 'active-link':''

app/views/businesses/_alphabar.html.slim
ul.list-inline
  -('a'..'z').to_a.each do |letter|
    li
      h5.text-uppercase=link_to letter, business_listings_path({search_letter: letter }), class: letter == @search_letter ? 'active-link':''

  li
    h5.text-uppercase=link_to "all", business_listings_path, class: @search_letter.blank? ? 'active-link':''

app/views/businesses/_form.html.slim
= simple_form_for([@parent, @business], html: {multipart: true}) do |f|
  .row
    .col-md-3
      .image#image-box.box-border.editable
        .edit-overlay
          i.fi-camera
          ' &nbsp; update profile picture
          = f.input :logo, as: :file, label: '&nbsp;'.html_safe
          = f.input :retained_logo, as: :hidden
        =image_tag (@business.logo_stored? ? @business.logo.url : 'default-business-pic.png'), id: 'profile-pic'
    .col-md-9
      .form-inputs
        .form-group
          .row
            .col-md-12= f.input :name, label: false, placeholder: 'Name', input_html:{class: 'form-control'}
      .form-inputs
        .form-group
          .row
            .col-md-4
              = f.input :phone_number, label: false, placeholder: 'Phone Number', input_html:{class: 'form-control'}
            .col-md-4
              = f.input :email, label: false, placeholder: 'Email', input_html:{class: 'form-control'}
            .col-md-4
              = f.input :working_hours, label: false, placeholder: 'Working Hours', input_html:{class: 'form-control'}
      .form-inputs
        .form-group
          .row
            .col-md-6
              = f.association :business_category, label: false, prompt: 'Business Type', input_html:{class: 'form-control'}
            .col-md-6
              = f.input :country, label: false, prompt: 'Country', input_html:{class: 'form-control'}
      .form-inputs
        .form-group
          .row
            .col-md-12
              = f.association :industries, as: :check_boxes, label: false, item_wrapper_class: 'checkbox-inline'
      .form-inputs
        .form-group
          .row
            .col-md-12
              = f.text_area :company_info,class: 'textarea', as: :text, label: false, placeholder: 'Company Info', input_html:{class: 'form-control '}
      .form-inputs
        .form-group
          .row
            .col-md-12
              =render 'shared/dynamic_map'
      .form-inputs
        .form-group
          .row
            .col-md-12
              = f.text_area :physical_location,class: 'textarea', label: false, placeholder: 'Physical Location', input_html:{class: 'form-control textarea'}
              = f.input :latitude, as: :hidden
              = f.input :longitude, as: :hidden

      .form-actions
        = f.button :submit, class: 'btn site-btn-primary pull-right'
javascript:
  $('body').on('click','input[type=submit]', function(){
    NProgress.start();
  });

app/views/businesses/_gallery_photos.html.slim
.row
  .col-md-4.reduced-padding.featured-profile-primary-pic
    =link_to business.gallery_photos.first do
      = image_tag business.gallery_photos.first.image.url if business.gallery_photos.first
  .col-md-8.reduced-padding
    - unless business.gallery_photos[1..6].nil?
      - business.gallery_photos[1..6].each do |photo|
        .col-md-3.reduced-padding.featured-profiles-grid.speciality-box
          = image_tag photo.image.url

app/views/businesses/_invite_page_admin.html.slim
#pageAdminModal
  h4#modalTitle Invite Page Admin
  hr
  .row
    .col-md-12
      = simple_form_for(:invitation, url: send_admin_invitation_business_path(@business)) do |f|
        .form-inputs
          .form-group
            .row
              .col-md-9
                = f.input :email_address, placeholder: 'Email', label: false, input_html:{class: 'form-control'}
          .form-actions
            = f.button :submit, "Invite Page Admin", class: 'btn site-btn-primary pull-right'

app/views/businesses/businesses_dashboard.html.slim
.section-container.specialities.margin-bottom-20
  .row
    .col-md-12
      h3.text-capitalize.no-margin-top Business
      #locale-links #{link_to 'local', request.path, class: @locale == 'local' ? 'active-link':'' } | #{link_to 'international', request.path + '?locale=international', class: @locale == 'international' ? 'active-link':''}
  .row
    .col-md-12.text-center.alphabar
      =render 'alphabar'
  .row.margin-bottom-20
    .col-md-12
      - Industry.all.each do |industry|
        =link_to business_listings_path(params:{industry: industry, locale: @locale}) do
          .col-md-2.speciality-box
            .image-text #{industry.name} (#{business_speciality_count(industry, @locale)})
            =image_tag "#{industry.name.downcase.gsub(' ', '_').gsub(',','')}.jpg"
  hr.hr
  - if get_ad("#{controller_name}_ad_1") && get_ad("#{controller_name}_ad_1").has_content?
    .row.site-ad
      .col-md-12.no-gutters
        = get_ad("#{controller_name}_ad_1").get_content
    hr.hr

  -unless @featured_businesses.empty?
    .row
      .col-md-12
        h4 Featured Businesses
    .row.margin-bottom-20
      .col-md-4.reduced-padding.featured-profile-primary-pic.large-dashboard-profile-pic
        =link_to @businesses.first do
          = image_tag artist_image(@businesses.first) if @businesses.first
          .media-image-text
            h4.text-uppercase= @businesses.first.name
            p= @businesses.first.industries.pluck(:name).join(', ')
            btn.btn view
            p= ISO3166::Country.find_country_by_alpha2(@businesses.first.country).name
      .col-md-8.reduced-padding.small-dashboard-profile-pics
        - unless @businesses[1..6].nil?
          - @businesses[1..6].each do |business|
            .col-md-3.reduced-padding.featured-profiles-grid
              = image_tag artist_image(business)
              .media-image-text
                h4.text-uppercase= business.name
                p= business.industries.pluck(:name).join(', ')
                btn.btn view
                
    hr.hr

  .row.clr.pro-header#business-listing
    #business-listing
      =render 'shared/business-listing'

app/views/businesses/edit.html.slim
.section-container
  .row
    .col-md-12
      h3 Editing #{@business.name}
  == render 'form'

app/views/businesses/new_news_event_blog.js.erb
<%- if @request == 'add a news story' %>
  $('#add-news-event-blog-modal').html("<%= escape_javascript render 'news_stories/remote_form' %>");
<%- elsif @request == 'add an event' %>
  $('#add-news-event-blog-modal').html("<%= escape_javascript render 'events/remote_form' %>");
<%- elsif @request == 'add a blog' %>
  $('#add-news-event-blog-modal').html("<%= escape_javascript render 'blogs/remote_form' %>");
<% end %>

$('#entityModal').modal()

tinyMCE.init({
  selector: 'textarea',
  menubar: false,
  statusbar: false,
  toolbar: 'bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  plugins: ['placeholder, link']
});

$('#event_date').datepicker({
  dateFormat: "dd-mm-yy"
});

$('#news_story_date, #blog_date').datepicker({
  dateFormat: "dd-mm-yy",
  maxDate: 0
});


$('#news_story_artist_id_tags, #blog_artist_id_tags, #event_artist_id_tags').tokenInput("/artists/token_inputs",{
  theme: "facebook",
  propertyToSearch: 'profile_name',
  hintText: 'Search for Artists'
});

$('#news_story_business_id_tags, #blog_business_id_tags').tokenInput("/businesses/token_inputs",{
  theme: "facebook",
  hintText: 'Search for Business'
});

$('#news_story_event_id_tags, #blog_event_id_tags').tokenInput("/events/token_inputs",{
  theme: "facebook",
  hintText: 'Search for Events'
});

$('#event_award_id_tags').tokenInput("/awards/token_inputs",{
  theme: "facebook",
  hintText: 'Search for Awards'
});

$('#token-input-event_award_id_tags').attr("placeholder", "Link Awards")

$('#token-input-news_story_artist_id_tags, #token-input-blog_artist_id_tags, #token-input-event_artist_id_tags').attr("placeholder", "Link Artists")
$('#token-input-news_story_event_id_tags, #token-input-blog_event_id_tags').attr("placeholder", "Link Events")
$('#token-input-news_story_business_id_tags, #token-input-blog_business_id_tags').attr("placeholder", "Link Businesses")

$('.modal').on('click','input[type=submit]', function(){
  NProgress.start();
});

app/views/businesses/request_ownership_transfer.js.erb
$('#manage-pages-modal').html("<%= escape_javascript render 'businesses/request_ownership_transfer' %>");

$('#pageAdminModal').modal()

app/views/businesses/show.html.slim
=title @business.name
=meta_description @description
.section-container
  .row.profile-details.margin-bottom-20.margin
    .col-md-3
      -if policy(@business).update?
        .pro-image#image-box.box-border.editable
          =simple_form_for @business do |f|
            .edit-overlay
              i.fi-camera
              ' &nbsp; update business picture
              = f.input :logo, as: :file, label: '&nbsp;'.html_safe
              = f.input :retained_logo, as: :hidden
            =f.submit 'Save Image', id: 'save-btn', class:'button btn site-btn-primary'
          =image_tag (@business.logo_stored? ? @business.logo.url : 'default-business-pic.png'), id: 'profile-pic'
      -else
        .pro-image
          =image_tag (@business.logo_stored? ? @business.logo.url : 'default-business-pic.png'), id: 'profile-pic'

    .col-md-9
      .row
        .col-md-12.no-gutters
          -if @business.verified?
            .verification.pull-right
              =image_tag "verified.svg"
          h3.no-margin-top.text-uppercase.text-primary= @business.name

      .row
        .col-md-12.no-gutters
          b Country:&nbsp;
          = ISO3166::Country.find_country_by_alpha2(@business.country).name
      .row
        .col-md-12.no-gutters
          b Industry:&nbsp;
          = @business.industries.pluck(:name).join(',')
      .row
        .col-md-12.no-gutters
          b Business Type:&nbsp;
          = @business.business_category.name

      .row
        .col-md-12.no-gutters
          = @business.company_info.html_safe?

      .row#profile-edit-links
        .col-md-1.col-md-offset-8.no-gutters
          =link_to 'Edit', edit_business_path(@business) if policy(@business).update?
        .col-md-3.no-gutters
          div[id="fan-section-business-#{@business.id}"]
            = business_fan_link(@business)

- if policy(@business).update?
  .profile-nav-bar
    .section-container
      .row
        .col-md-12.prof-nav
          ul.list-inline
            li
              h4=link_to 'Add an artist', new_business_artist_path(@business), class: 'add-news-event-blog-btn btn site-btn-primary'

      hr.hr
.featured-section
  .section-container
    .row
      .col-md-12
        h3 GALLERY
    - if policy(@business).update?
      .row
        .col-md-12
          #progress
            .bar style=("width: 0%;")
          =simple_form_for([@business,GalleryPhoto.new]) do |f|
            = f.input :image, as: :file, label: false, input_html:{multiple: true, name: 'gallery_photo[image]', class: 'input-1 btn btn-default'}

    - if @business.gallery_photos.present? || !current_user.nil? && policy(@business).update?
      #gallery-photos
        =render partial: 'gallery_photos', locals:{business: @business}
      hr.hr

.business-contacts#contacts
  .section-container
    .row
      .col-md-12
        h3 CONTACTS
    .row
      .col-md-8.contacts-map-images
        = render 'shared/static_map'
      .col-md-4
        h6 Contacts
        #contact-details
          = render 'contact_details'

        h6 Links:
        #link-details
          - @business.links.each do |link|
            = render 'links_partial', link: link
        .row
          .col-md-12 =link_to 'add links', new_link_business_path(@business), :remote => true if policy(@business).update?
    hr.hr

-if !@work.empty? || !current_user.nil? && policy(@business).update?
  .business-works#work-header
    .section-container
      .row
        .col-md-12
          h3 WORKS
      - if policy(@business).update?
        .row
          .col-md-12
            ul.list-inline.add-items-links
              li
                =link_to 'add production', '#', class: 'add-entity-select-box btn site-btn-primary', title: 'add a production', :onclick => "findBusinessForm(#{@business.id}, 'entities', 'production')"
      -if !@work.empty?
        .dash-filters
          .row
            .col-md-4
              .form-group
                = collection_select(:filter, :industry_id, Industry.all, :id, :name, {prompt: 'Select category to filter results'}, {class: 'form-control'})
            .col-md-4
              .form-group
                = text_field_tag 'filter[date]', nil, placeholder: 'Select date to filter results', class: 'form-control'
            .col-md-4
              .form-group
                = select_tag "filter[data-type]", options_for_select(['Book', 'PhotoArt', 'Production', 'Song', 'Collection Album']), class: 'form-control', prompt: "Select a data type to filter results"

      .row#business-works
        = render 'works'
    hr.hr

-if policy(@business).update? || !@business.awards.empty?
  .business-awards#awards-header
    .section-container
      .row
        .col-md-12
          h3 AWARDS
      - if policy(@business).update?
        .row
          .col-md-12
            ul.add-items-links.list-inline
              li
                =link_to 'Add an award', new_business_award_path(@business), class: 'add-news-event-blog-btn btn site-btn-primary', title: 'Add a news story'
      .row#awards
        - @business.awards.each do |award|
          .col-md-3
            =link_to award_url(award,{params:{year: 1.year.ago.year}}) do
              =image_tag award.image_stored? ? award.image.url : 'default-award-pic.png'
      hr.hr

-unless @news_events_blogs.empty? && !policy(@business).update?
  .business-events-news-blogs.margin-bottom-20#news-stories-header
    .section-container
      .row
        .col-md-12
          h3 NEWS, BLOGS AND EVENTS
      - if policy(@business).update?
        .row
          .col-md-12
            ul.add-items-links.list-inline
              li
                =link_to 'add news story', new_business_news_story_path(@business), class: 'add-news-event-blog-btn btn site-btn-primary', title: 'Add a news story'
              li.clr
                =link_to 'add blog', new_business_blog_path(@business), class: 'add-news-event-blog-btn btn site-btn-primary', title: 'Add a blog'
              li.clr
                =link_to 'add event', '#', class: 'add-news-event-blog-btn btn site-btn-primary', title: 'Add an event', :onclick => "findBusinessForm(#{@business.id}, 'news_event_blog', 'Add an event')"

      .row#news-events-blogs-cards
        - @news_events_blogs.each do |card|
          .col-md-3.reduced-padding[id = "#{card.class.name.downcase}-#{card.id}"]
            -if card.is_a?(Event)
              = render partial: 'shared/event-card', locals:{event: card}
            -else
              = render partial: 'shared/blog-news-card', locals:{card: card}

strong SHARE THIS BUSINESS
= social_share_button_tag(@business.name, :url => "#{request.original_url}", desc: "#{@description}", via: "Me") 


#add-contacts-modal
#add-news-event-blog-modal
#add-work-entity-modal
#suggested-update-modal
#add-links-modal


javascript:
  $(function(){
    $('#filter_date').datepicker({
      dateFormat: "dd-mm-yy"
    });

    $( "#filter_industry_id, #filter_date, #filter_data-type" ).change(function() {
      $.ajax({
        url: "/businesses/#{@business.id}",
        data: {
          industry_id: $('#filter_industry_id').val(),
          date: $('#filter_date').val(),
          data_type: $('#filter_data-type').val()
          },
        dataType: 'script'
      });
    });
  });