config/routes.rb
Rails.application.routes.draw do
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :impressions

  ###########
  # admin routes
  ###########
  namespace :admin do
    resources :business_categories
    
    resources :businesses do
      resources :gallery_photos, only: [ :new, :create]
      member do
        patch :ban
        patch :verify
        patch :change_featured_status
        get :invite_page_admin
        post :send_admin_invitation
        get :request_ownership_transfer
        patch :transfer_ownership
      end
    end
    resources :admins do
      member do
        patch :activate_deactivate
        patch :reset_password
      end
    end
    resources :users, only: [:index, :show] do
      member do
        patch :ban
      end
    end
    resources :slider_images
    resources :artists do
      resources :gallery_photos, only: [ :new, :create]
      member do
        patch :change_status
        patch :change_featured_status
        patch :verify
        get :invite_page_admin
        post :send_admin_invitation
        get :request_ownership_transfer
        patch :transfer_ownership
      end
    end
    resources :awards, :events, :gallery_photos, :life_events, :news_stories, :collection_albums, :blogs, :songs, :books, :photo_arts, :productions, :suggested_updates, except: [:new, :delete] do
      member do
        patch :change_status
        patch :ban
      end
    end

    resources :events do
      member do
        patch :change_featured_status
      end
    end
    resources :sites

    resources :site_ads
    get 'dashboard' => 'pages#dashboard'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    root 'sessions#new'
  end

  resources :users, shallow: :true do
    resources :artists, only: [:new, :create]
    resources :businesses, only: [:new, :create]
    member do
      get :confirm_email
      get :dashboard
      get :accept_admin_invitation
      get :confirm_email
      get 'edit_profile_pic' => 'users#edit_profile_pic'
      get 'fanned_artists'
      get 'liked_businesses'
      get 'entity_management'
    end
  end

  #sign_up routes
  get 'signup' => 'users#new'

  # Sessions routes
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroyuser'

  get 'load_specialities' => 'artists#load_specialities'
  get 'terms_and_conditions' => 'pages#terms_and_conditions'
  get 'privacy' => 'pages#privacy'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # autocomplete routes
  get 'autocomplete_director_name' => 'productions#get_directors'
  get 'autocomplete_production_company_name' => 'productions#get_production_companies'
  get 'autocomplete_production_language' => 'productions#get_production_languages'
  get 'autocomplete_publishing_company_name' => 'books#get_publishing_companies'
  get 'autocomplete_event_venues' => 'events#get_venues'

  get 'autocomplete_nominee/:award_category_id' => 'nominees#get_nominee', as: :autocomplete_nominee

  get 'search' => 'search#get_results', as: :search
  get 'music_artist_listings' => 'artists#music_artist_listings', as: :music_artist_listings
  get 'photo_art_artist_listings' => 'artists#photo_art_artist_listings', as: :photo_art_artist_listings
  get 'fashion_artist_listings' => 'artists#fashion_artist_listings', as: :fashion_artist_listings
  get 'literature_artist_listings' => 'artists#literature_artist_listings', as: :literature_artist_listings
  get 'production_artist_listings' => 'artists#production_artist_listings', as: :production_artist_listings

  get 'artist_listings' => 'artists#artist_listings', as: :artist_listings
  get 'business_listings' => 'businesses#business_listings', as: :business_listings
  get 'item_listings' => 'search#item_listings', as: :item_listings
  get 'media_listings' => 'media#media_listings', as: :media_listings
  get 'awards_listings' => 'awards#awards_listings', as: :awards_listings

  get 'music' => 'songs#music_dashboard', as: :music_dashboard
  get 'arts' => 'photo_arts#photo_arts_dashboard', as: :photo_arts_dashboard
  get 'fashion' => 'artists#fashion_dashboard', as: :fashion_dashboard
  get 'literature' => 'books#literature_dashboard', as: :literature_dashboard
  get 'film' => 'productions#productions_dashboard', as: :productions_dashboard
  get 'business' => 'businesses#businesses_dashboard', as: :businesses_dashboard
  get 'events' => 'events#events_dashboard', as: :events_dashboard
  get 'media' => 'media#media_dashboard', as: :media_dashboard
  get 'awards' => 'awards#awards_dashboard', as: :awards_dashboard
  get 'deletephoto/:id' => 'gallery_photos#destroy'
  get "presskit" => 'artists#presskit', as: :presskit
  get "deactivate/:id" => 'users#ban', as: :deactivate

  root 'pages#homepage'

  resources :artists, path: "" do
    member do
      get 'add_remove_fan'
    end
  end

  resources :businesses, path: "/business" do
    member do
      get 'add_remove_fan'
    end
  end

  resources :artists, :businesses, shallow: :true do
    collection do
      get :token_inputs
    end
      resources :events, :life_events, :news_stories, :blogs, only: [:new, :create],  shallow: :true do
      resources :gallery_photos
    end

    resources :songs, only: [:new, :create]
    resources :books, only: [:new, :create]
    resources :photo_arts, only: [:new, :create]
    resources :productions, only: [:new, :create]
    resources :links
    resources :collection_albums
    resources :suggested_updates
    member do
      get :invite_page_admin
      post :send_admin_invitation
      get :request_ownership_transfer
      patch :transfer_ownership
      get :contacts
      get :book_token_inputs
      get :production_token_inputs
      get :song_token_inputs
      get :photo_art_token_inputs
      get :award_token_inputs
      get :collection_album_token_inputs
    end
  end

  resources :awards, shallow: :true do
    collection do
      get :token_inputs
    end
  end

  resources :businesses, shallow: :true do
    member do
      get 'add_remove_fan'
    end
    resources :artists
    resources :awards, shallow: :true do
    resources :gallery_photos
      member do
        get :show_awards_categories
        resources :award_categories, shallow: :true do
          member do
            resources :nominees
          end
        end
      end
    end
  end

  resources :events, :gallery_photos, :life_events, :news_stories, :blogs, :songs, :books, :photo_arts, :productions do
    member do
      get :publish
    end
    collection do
      get :token_inputs
    end
    get :publish
  end

  #this is for adding entities
  resources :artists do
    member do
      get :new_link
      post :create_link
      get :new_life_event
      post :create_life_event
      get :new_entity
      post :create_entity
      get :new_news_event_blog
      post :create_news_event_blog
      get :create_news_event_blog
      get :publish
    end
    get :publish
    resources :gallery_photos, only: [:new, :create]
  end

  resources :businesses do
    member do
      get :new_news_event_blog
      post :create_news_event_blog
      get :new_link
      post :create_link
      get :new_entity
      post :create_entity
    end
    resources :gallery_photos, only: [:new, :create]
  end
  #########

  resources :password_resets

  #omniauth routing
  get '/auth/:provider/callback', to: 'sessions#omniauth_create', as: 'omniauth_create'

  match '*a', :to => redirect('/'), via: [:get, :post]
end

app/models/collection_album.rb
# == Schema Information
#
# Table name: collection_albums
#
#  id                 :integer          not null, primary key
#  title              :string
#  description        :text
#  visible            :boolean
#  parent_id          :integer
#  parent_type        :string
#  collection_type_id :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  cover_pic_uid      :string
#  album_date         :date
#  slug               :string
#  aasm_state         :string
#
# Indexes
#
#  index_collection_albums_on_slug  (slug)
#

class CollectionAlbum < ApplicationRecord
  extend FriendlyId
  include EntityState
  include PgSearch

  multisearchable against: %i(title description)

  belongs_to :parent, polymorphic: true
  validates_presence_of :title, :description
  has_many :collection_entities, :dependent => :destroy
  has_many :books, through: :collection_entities, source: :entity, source_type: "Book"
  has_many :photo_arts, through: :collection_entities, source: :entity, source_type: "PhotoArt"
  has_many :productions, through: :collection_entities, source: :entity, source_type: "Production"
  has_many :songs, through: :collection_entities, source: :entity, source_type: "Song"
  has_many :impressions, as: :entity, dependent: :destroy
  has_many :gallery_photos, as: :parent, :dependent => :destroy
  has_and_belongs_to_many :life_events

  attr_reader :book_id_tags, :song_id_tags, :photo_art_id_tags, :production_id_tags

  friendly_id :title, use: [:slugged, :history]
  dragonfly_accessor :cover_pic

  default_scope -> {order('created_at desc')}
  scope :published, lambda{where(:aasm_state => 'published')}
  scope :verified, lambda { where(:parent => true) }

  def date
    album_date
  end

  def photo_art_id_tags=(val)
    self.photo_art_ids = val.split(",")
  end

  def song_id_tags=(val)
    self.song_ids = val.split(",")
  end

  def production_id_tags=(val)
    self.production_ids = val.split(",")
  end

  def book_id_tags=(val)
    self.book_ids = val.split(",")
  end

  def country
    ISO3166::Country.find_country_by_alpha2(parent.country_of_birth).name
  end

  def self.trending
    return Impression.where(entity_type: 'CollectionAlbum').where('created_at >= ?', 1.week.ago).group(:entity_id).order('count_id desc').count('id').collect{|collection_album_id,count| CollectionAlbum.find_by_id(collection_album_id).parent}.compact
  end

  def self.viewable
    all.collect do |collection_album|
      collection_album if collection_album.aasm_state == 'published' || collection_album.parent.verified
    end.compact
  end

end

app/controllers/admin/collection_albums_controller.rb
class Admin::CollectionAlbumsController < Admin::AdminController
  before_action :set_collection_album, only: [:show, :change_status]

  def index
    @collection_albums = if current_admin.content_administrator?
      artists = current_admin.industries.collect{|industry| industry.artists}.flatten!.uniq
      artists.map(&:collection_albums).flatten
    else
      CollectionAlbum.all
    end
  end

  def change_status
    respond_to do |format|
      case params[:status]
      when 'unpublish'
        if @collection_album.unpublish!
          format.html { redirect_to polymorphic_path([:admin, @collection_album]), notice: 'collection_album was successfully unpublish.' }
          format.json { render :show, status: :ok, location: @collection_album }
          format.js { render partial: 'admin/shared/change_entity_status',locals: {entity: @collection_album }}
        else
          format.html { redirect_to polymorphic_path([:admin, @collection_album]), notice: 'collection_album was not successfully unpublish.' }
          format.json { render :show, status: :ok, location: @collection_album }
          format.js {render partial: 'shared/errors', locals: {entity: @collection_album }}
        end
      when 'publish'
        if @collection_album.approve!
          format.html { redirect_to polymorphic_path([:admin, @collection_album]), notice: 'collection_album was successfully edited.' }
          format.json { render :show, status: :ok, location: @collection_album }
          format.js { render partial: 'admin/shared/change_entity_status',locals: {entity: @collection_album }}
        else
          format.html { redirect_to polymorphic_path([:admin, @collection_album]), notice: 'collection_album was not successfully edited.' }
          format.json { render :show, status: :ok, location: @collection_album }
          format.js {render partial: 'shared/errors', locals: {entity: @collection_album }}
        end
      else
        format.html { redirect_to polymorphic_path([:admin, @collection_album]), notice: 'collection_album was not successfully updated.' }
        format.json { render :show, status: :ok, location: @collection_album }
        format.js {render partial: 'shared/errors', locals: {entity: @collection_album }}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection_album
      @collection_album = CollectionAlbum.friendly.find(params[:id])
    end
end

app/controllers/collection_albums_controller.rb
class CollectionAlbumsController < ApplicationController
  skip_before_action :require_login, only: :show
  before_action :set_collection_album, only: [:show, :edit, :update, :destroy]
  before_action :load_parent, only: [:new, :create]

  # GET /collection_albums
  # GET /collection_albums.json
  def index
    @collection_albums = CollectionAlbum.all
  end

  # GET /collection_albums/1
  # GET /collection_albums/1.json
  def show
    @collection_album.impressions.create!
    @description = ActionView::Base.full_sanitizer.sanitize(@collection_album.description).split(/\s+/).slice(0,300).join(' ');
  end

  # GET /collection_albums/new
  def new
    @collection_album = @parent.collection_albums.build
  end

  # GET /collection_albums/1/edit
  def edit
  end

  # POST /collection_albums
  # POST /collection_albums.json
  def create
    @collection_album = @parent.collection_albums.build(collection_album_params)

    respond_to do |format|
      if @collection_album.save
        format.html { redirect_to @collection_album, notice: 'Collection album was successfully created.' }
        format.json { render :show, status: :created, location: @collection_album }
      else
        format.html { render :new }
        format.json { render json: @collection_album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collection_albums/1
  # PATCH/PUT /collection_albums/1.json
  def update
    respond_to do |format|
      if @collection_album.update(collection_album_params)
        @artist = @collection_album.parent
        @id = "collectionalbum-#{@collection_album.id}"
        format.html { redirect_to @collection_album, notice: 'Collection Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection_album }
        format.js { render :update}
      else
        format.html { render :edit }
        format.js { render partial: 'shared/errors', locals: {entity: @collection_album} }
      end
    end
  end

  # DELETE /collection_albums/1
  # DELETE /collection_albums/1.json
  def destroy
    @collection_album.destroy
    respond_to do |format|
      format.html { redirect_to collection_albums_url, notice: 'Collection album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection_album
      @collection_album = CollectionAlbum.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_album_params
      params.require(:collection_album).permit(:title, :description, :parent_id, :parent_id, :album_date, :cover_pic,
      :retained_cover_pic, :parent_type, :book_id_tags, :song_id_tags, :photo_art_id_tags, :production_id_tags)
    end
end

app/views/collection_albums/_form.html.slim
= simple_form_for([@parent, @collection_album]) do |f|
  = f.error_notification

  .form-inputs
    = f.association :collection_type
    = f.input :name
    = f.input :description
    section#entities
      h3 Please select your items below
      #books.entity-class
        = f.association :books, as: :check_boxes
      #songs.entity-class
        = f.association :songs, as: :check_boxes
      #photo_arts.entity-class
        = f.association :photo_arts, as: :check_boxes
      #productions.entity-class
        = f.association :productions, as: :check_boxes

  .form-actions
    = f.button :submit


javascript:
  $(function(){
    $('#collection_album_collection_type_id').on('change', function(){
      $('.entity-class').hide();
      $('#entities').show();

      switch($("#collection_album_collection_type_id option:selected").text()){
        case("Books"):
          $('#books').show();
          break;
        case("Music"):
          $('#songs').show();
          break;
        case("Photos/Art"):
          $('#photo_arts').show();
          break;
        case("Productions"):
          $('#productions').show();
          break;
        default:
          $('#entities').hide();
          $('.entity-class').hide();
        }
    });
    $('#entities').hide();
  })

app/views/collection_albums/_remote_form.html.slim
#entityModal.reveal[data-reveal]
  -if @collection_album.new_record?
    h4#modalTitle
      | Add a New Collection
    p
    hr
    .row
      .col-md-12
        = simple_form_for([@parent, @collection_album], html: {multipart: true}, remote: true, url: create_entity_artist_path(@parent)) do |f|
          .form-inputs
            .form-group
              .row
                .col-md-9
                  = f.input :title, label: false, placeholder: 'Title', input_html:{class: 'form-control'}
                .col-md-3
                  = f.input :album_date, as: :string, label: false, placeholder: 'Date', input_html:{class: 'form-control'}

          .form-inputs
            .form-group
              .row
                .col-md-12
                  = f.input :description, label: false, placeholder: 'Description', input_html:{class: 'form-control'}
          section#entities
            h5 Add entities to this collection/album
          .form-inputs
            .form-group
              .row
                .col-md-6
                  = f.input :book_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.books.map(&:attributes).to_json }, label: 'Books', label: false
                .col-md-6
                  = f.input :song_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.songs.map(&:attributes).to_json }, label: 'Songs', label: false
              .row
                .col-md-6
                  = f.input :photo_art_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.photo_arts.map(&:attributes).to_json }, label: 'Photos/Art', label: false
                .col-md-6
                  = f.input :production_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.productions.map(&:attributes).to_json }, label: 'Productions', label: false
          .form-inputs
            .form-group
              .row
                .col-md-6
                  = f.input :cover_pic, as: :file, label: false
                .col-md-6.modal-image-text Select an appropriate cover photo for this album
          .form-actions
            = f.button :submit, class: 'btn site-btn-primary pull-right'
  -else
    h4#modalTitle
      | Edit Collection
    p
    hr
    .row
      .col-md-12
        = simple_form_for(@collection_album, html: {multipart: true}, remote: true) do |f|
          .form-inputs
            .form-group
              .row
                .col-md-9
                  = f.input :title, label: false, placeholder: 'Title', input_html:{class: 'form-control'}
                .col-md-3
                  = f.input :album_date, as: :string, label: false, placeholder: 'Date', input_html:{class: 'form-control'}

          .form-inputs
            .form-group
              .row
                .col-md-12
                  = f.input :description, label: false, placeholder: 'Description', input_html:{class: 'form-control'}
          section#entities
            h5 Add entities to this collection/album
          .form-inputs
            .form-group
              .row
                .col-md-6
                  = f.input :book_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.books.map(&:attributes).to_json }, label: 'Books', label: false
                .col-md-6
                  = f.input :song_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.songs.map(&:attributes).to_json }, label: 'Songs', label: false
              .row
                .col-md-6
                  = f.input :photo_art_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.photo_arts.map(&:attributes).to_json }, label: 'Photos/Art', label: false
                .col-md-6
                  = f.input :production_id_tags, :input_html => {class: 'form-control', "data-pre" => @collection_album.productions.map(&:attributes).to_json }, label: 'Productions', label: false
          .form-inputs
            .form-group
              .row
                .col-md-6
                  = f.input :cover_pic, as: :file, label: false
                .col-md-6.modal-image-text Select an appropriate cover photo for this album
          .form-actions
            = f.button :submit, class: 'btn site-btn-primary pull-right'

app/views/collection_albums/edit.html.slim
h1 Editing collection_album

== render 'form'

= link_to 'Show', @collection_album
'|

app/views/collection_albums/edit.js.erb
$('#add-work-entity-modal').html("<%= escape_javascript render 'collection_albums/remote_form' %>");

$('#entityModal').modal()

tinyMCE.init({
  selector: 'textarea',
  menubar: false,
  statusbar: false,
  toolbar: 'bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  plugins: ['placeholder, link']
});

$('#collection_album_album_date').datepicker({
  dateFormat: "dd-mm-yy",
  maxDate: "#{Date.today}"
});


$('#collection_album_song_id_tags').tokenInput('/songs/token_inputs',{
  theme: "facebook",
  propertyToSearch: 'title',
  hintText: 'Search for Songs'
});

$('#collection_album_book_id_tags').tokenInput('/books/token_inputs',{
  theme: "facebook",
  propertyToSearch: 'title',
  hintText: 'Search for Books'
});

$('#collection_album_photo_art_id_tags').tokenInput('/photo_arts/token_inputs',{
  theme: "facebook",
  propertyToSearch: 'title',
  hintText: 'Search for Photos or Art'
});

$('#collection_album_production_id_tags').tokenInput('/productions/token_inputs',{
  theme: "facebook",
  propertyToSearch: 'title',
  hintText: 'Search for Productions'
});

$('#token-input-collection_album_song_id_tags').attr("placeholder", "Link Songs")
$('#token-input-collection_album_book_id_tags').attr("placeholder", "Link Books")
$('#token-input-collection_album_production_id_tags').attr("placeholder", "Link Productions")
$('#token-input-collection_album_photo_art_id_tags').attr("placeholder", "Link Photos/Art")

$('.modal').on('click','input[type=submit]', function(){
  NProgress.start();
});

app/views/collection_albums/index.html.slim
h1 Listing collection_albums

table
  thead
    tr
      th Type
      th Name
      th Description
      th Parent
      th Parent type
      th
      th
      th

  tbody
    - @collection_albums.each do |collection_album|
      tr
        td = collection_album.type_id
        td = collection_album.name
        td = collection_album.description
        td = collection_album.parent_id
        td = collection_album.parent_type
        td = link_to 'Show', collection_album
        td = link_to 'Edit', edit_collection_album_path(collection_album)
        td = link_to 'Destroy', collection_album, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Collection album', new_collection_album_path

app/views/collection_albums/new.html.slim
.row
  .medium-5.medium-offset-2.columns
    h1 New collection_album

    == render 'form'

app/views/collection_albums/show.html.slim
=title @collection_album.title
=meta_description @description
.row.single-entity-page
  .col-md-12
    .section-container.padding-bottom-20
      .row
        .col-md-12.entity-page-entity-image
          =image_tag entity_image(@collection_album)
      .row
        .col-md-6.no-gutters
          .row
            .col-md-12
              h3.no-margin-top.text-uppercase= @collection_album.title
          .row
            .col-md-12
              <b>Owner:</b> #{link_to @collection_album.parent.profile_name, @collection_album.parent}
          .row
            .col-md-12
              <b>Country:</b> #{ISO3166::Country.find_country_by_alpha2(@collection_album.parent.country_of_birth).name}
          .row
            .col-md-12
              <b>Date Created:</b> #{@collection_album.album_date.strftime("#{@collection_album.album_date.day.ordinalize} %B %Y") if @collection_album.album_date }
        .col-md-6.no-gutters
          = @collection_album.description.html_safe

    .section-container.padding-bottom-20
      .row
        .col-md-12
          h3.text-uppercase collection items
      .row
        .col-md-12
          .row#collection-entities
            - @collection_album.collection_entities.each do |entity|
              .col-md-1-5.reduced-gutters
                = render partial: 'shared/entity-image-tiles', locals: {entity: entity.entity}

    =render partial: 'shared/related_items', locals:{relatable_item: @collection_album}

    .row
      .col-md-12.text-center.margin-top-20
        .row
          .col-md-3.col-md-offset-3#fan-button
            = render partial: 'shared/fan_button', locals: {parent: @collection_album.parent}
          .col-md-2
            = link_to 'Back', @collection_album.parent, class: 'btn site-btn-primary'

app/views/collection_albums/update.js.erb
var id = "#<%= @id %>"
$(id).html("<%= escape_javascript render partial: 'artists/artist-work-entity', locals:{entity: @collection_album} %>")
$.modal.close();
$('#add-work-entity-modal').empty();

NProgress.done();