config/routes.rb
Rails.application.routes.draw do
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  resources :impressions

  ###########
  # admin routes
  ###########
  namespace :admin do
    resources :business_categories
    
    resources :businesses do
      resources :gallery_photos, only: [ :new, :create]
      member do
        patch :ban
        patch :verify
        patch :change_featured_status
        get :invite_page_admin
        post :send_admin_invitation
        get :request_ownership_transfer
        patch :transfer_ownership
      end
    end
    resources :admins do
      member do
        patch :activate_deactivate
        patch :reset_password
      end
    end
    resources :users, only: [:index, :show] do
      member do
        patch :ban
      end
    end
    resources :slider_images
    resources :artists do
      resources :gallery_photos, only: [ :new, :create]
      member do
        patch :change_status
        patch :change_featured_status
        patch :verify
        get :invite_page_admin
        post :send_admin_invitation
        get :request_ownership_transfer
        patch :transfer_ownership
      end
    end
    resources :awards, :events, :gallery_photos, :life_events, :news_stories, :collection_albums, :blogs, :songs, :books, :photo_arts, :productions, :suggested_updates, except: [:new, :delete] do
      member do
        patch :change_status
        patch :ban
      end
    end

    resources :events do
      member do
        patch :change_featured_status
      end
    end
    resources :sites

    resources :site_ads
    get 'dashboard' => 'pages#dashboard'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    root 'sessions#new'
  end

  resources :users, shallow: :true do
    resources :artists, only: [:new, :create]
    resources :businesses, only: [:new, :create]
    member do
      get :confirm_email
      get :dashboard
      get :accept_admin_invitation
      get :confirm_email
      get 'edit_profile_pic' => 'users#edit_profile_pic'
      get 'fanned_artists'
      get 'liked_businesses'
      get 'entity_management'
    end
  end

  #sign_up routes
  get 'signup' => 'users#new'

  # Sessions routes
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroyuser'

  get 'load_specialities' => 'artists#load_specialities'
  get 'terms_and_conditions' => 'pages#terms_and_conditions'
  get 'privacy' => 'pages#privacy'
  get 'about' => 'pages#about'
  get 'help' => 'pages#help'

  # autocomplete routes
  get 'autocomplete_director_name' => 'productions#get_directors'
  get 'autocomplete_production_company_name' => 'productions#get_production_companies'
  get 'autocomplete_production_language' => 'productions#get_production_languages'
  get 'autocomplete_publishing_company_name' => 'books#get_publishing_companies'
  get 'autocomplete_event_venues' => 'events#get_venues'

  get 'autocomplete_nominee/:award_category_id' => 'nominees#get_nominee', as: :autocomplete_nominee

  get 'search' => 'search#get_results', as: :search
  get 'music_artist_listings' => 'artists#music_artist_listings', as: :music_artist_listings
  get 'photo_art_artist_listings' => 'artists#photo_art_artist_listings', as: :photo_art_artist_listings
  get 'fashion_artist_listings' => 'artists#fashion_artist_listings', as: :fashion_artist_listings
  get 'literature_artist_listings' => 'artists#literature_artist_listings', as: :literature_artist_listings
  get 'production_artist_listings' => 'artists#production_artist_listings', as: :production_artist_listings

  get 'artist_listings' => 'artists#artist_listings', as: :artist_listings
  get 'business_listings' => 'businesses#business_listings', as: :business_listings
  get 'item_listings' => 'search#item_listings', as: :item_listings
  get 'media_listings' => 'media#media_listings', as: :media_listings
  get 'awards_listings' => 'awards#awards_listings', as: :awards_listings

  get 'music' => 'songs#music_dashboard', as: :music_dashboard
  get 'arts' => 'photo_arts#photo_arts_dashboard', as: :photo_arts_dashboard
  get 'fashion' => 'artists#fashion_dashboard', as: :fashion_dashboard
  get 'literature' => 'books#literature_dashboard', as: :literature_dashboard
  get 'film' => 'productions#productions_dashboard', as: :productions_dashboard
  get 'business' => 'businesses#businesses_dashboard', as: :businesses_dashboard
  get 'events' => 'events#events_dashboard', as: :events_dashboard
  get 'media' => 'media#media_dashboard', as: :media_dashboard
  get 'awards' => 'awards#awards_dashboard', as: :awards_dashboard
  get 'deletephoto/:id' => 'gallery_photos#destroy'
  get "presskit" => 'artists#presskit', as: :presskit
  get "deactivate/:id" => 'users#ban', as: :deactivate

  root 'pages#homepage'

  resources :artists, path: "" do
    member do
      get 'add_remove_fan'
    end
  end

  resources :businesses, path: "/business" do
    member do
      get 'add_remove_fan'
    end
  end

  resources :artists, :businesses, shallow: :true do
    collection do
      get :token_inputs
    end
      resources :events, :life_events, :news_stories, :blogs, only: [:new, :create],  shallow: :true do
      resources :gallery_photos
    end

    resources :songs, only: [:new, :create]
    resources :books, only: [:new, :create]
    resources :photo_arts, only: [:new, :create]
    resources :productions, only: [:new, :create]
    resources :links
    resources :collection_albums
    resources :suggested_updates
    member do
      get :invite_page_admin
      post :send_admin_invitation
      get :request_ownership_transfer
      patch :transfer_ownership
      get :contacts
      get :book_token_inputs
      get :production_token_inputs
      get :song_token_inputs
      get :photo_art_token_inputs
      get :award_token_inputs
      get :collection_album_token_inputs
    end
  end

  resources :awards, shallow: :true do
    collection do
      get :token_inputs
    end
  end

  resources :businesses, shallow: :true do
    member do
      get 'add_remove_fan'
    end
    resources :artists
    resources :awards, shallow: :true do
    resources :gallery_photos
      member do
        get :show_awards_categories
        resources :award_categories, shallow: :true do
          member do
            resources :nominees
          end
        end
      end
    end
  end

  resources :events, :gallery_photos, :life_events, :news_stories, :blogs, :songs, :books, :photo_arts, :productions do
    member do
      get :publish
    end
    collection do
      get :token_inputs
    end
    get :publish
  end

  #this is for adding entities
  resources :artists do
    member do
      get :new_link
      post :create_link
      get :new_life_event
      post :create_life_event
      get :new_entity
      post :create_entity
      get :new_news_event_blog
      post :create_news_event_blog
      get :create_news_event_blog
      get :publish
    end
    get :publish
    resources :gallery_photos, only: [:new, :create]
  end

  resources :businesses do
    member do
      get :new_news_event_blog
      post :create_news_event_blog
      get :new_link
      post :create_link
      get :new_entity
      post :create_entity
    end
    resources :gallery_photos, only: [:new, :create]
  end
  #########

  resources :password_resets

  #omniauth routing
  get '/auth/:provider/callback', to: 'sessions#omniauth_create', as: 'omniauth_create'

  match '*a', :to => redirect('/'), via: [:get, :post]
end

app/models/award.rb
# == Schema Information
#
# Table name: awards
#
#  id          :integer          not null, primary key
#  name        :string
#  business_id :integer
#  details     :text
#  image_uid   :string
#  country     :string
#  start_year  :integer
#  industry_id :integer
#  slug        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  aasm_state  :string
#
# Indexes
#
#  index_awards_on_slug  (slug) UNIQUE
#

class Award < ApplicationRecord
  extend FriendlyId
  include PgSearch
  include EntityState

  multisearchable against: %i(name details)

  friendly_id :name, use: [:slugged, :history]

  belongs_to :business
  belongs_to :industry

  has_many :award_categories, :dependent => :destroy
  has_many :nominees, through: :award_categories, :dependent => :destroy
  has_many :gallery_photos, as: :parent, :dependent => :destroy
  has_and_belongs_to_many :blogs
  has_and_belongs_to_many :events
  has_and_belongs_to_many :news_stories

  dragonfly_accessor :image

  validates_presence_of :name, :details, :industry_id

  default_scope -> {order('created_at desc')}

  scope :viewable, -> { where(aasm_state: [:approved,:approved_with_changes])}
  
end

app/controllers/admin/awards_controller.rb
class Admin::AwardsController < Admin::AdminController
  before_action :set_award, only: [:show, :change_status]

  def index
    @awards = if current_admin.content_administrator?
      businesses = current_admin.industries.collect{|industry| industry.businesses}.flatten!.uniq
      businesses.map(&:awards).flatten
    else
      Award.all
    end
  end

  def change_status
    respond_to do |format|
      case params[:status]
      when 'unpublish'
        if @award.unpublish!
          format.html { redirect_to polymorphic_path([:admin, @award]), notice: 'award was successfully unpublish.' }
          format.json { render :show, status: :ok, location: @award }
        else
          format.html { redirect_to polymorphic_path([:admin, @award]), notice: 'award was not successfully unpublish.' }
          format.json { render :show, status: :ok, location: @award }
        end
      when 'publish'
        if @award.approve!
          format.html { redirect_to polymorphic_path([:admin, @award]), notice: 'award was successfully edited.' }
          format.json { render :show, status: :ok, location: @award }
        else
          format.html { redirect_to polymorphic_path([:admin, @award]), notice: 'award was not successfully edited.' }
          format.json { render :show, status: :ok, location: @award }
        end
      else
        format.html { redirect_to polymorphic_path([:admin, @award]), notice: 'award was not successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = Award.friendly.find(params[:id])
    end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  skip_before_action :require_login, only: [:show, :show_awards_categories, :awards_dashboard, :awards_listings]
  before_action :set_award, only: [:show, :edit, :update, :destroy, :show_awards_categories]
  before_action :load_parent, only: [:new, :create]

  # GET /awards
  # GET /awards.json
  def index
    @awards = Award.all
  end

  def awards_dashboard
    @arts = Industry.find(1).awards.last(10)
    @fashion = Industry.find(2).awards.last(10)
    @films = Industry.find(3).awards.last(10)
    @literatures = Industry.find(4).awards.last(10)
    @musics = Industry.find(5).awards.last(10)

    @category_count = {
      'arts_awards' => @arts.count,
      'fashion_awards' => @fashion.count,
      'film_awards' => @films.count,
      'literature_awards'=> @literatures.count ,
      'music-awards' => @musics.count    
    }
  end

  def awards_listings
    @search_letter = params[:search_letter]
    @locale = params[:locale] || 'local'
    @request_path = request.path

    if params[:industry].present?
      @industry = params[:industry];
      @items = if @industry == "arts_awards"
        Industry.find(1).awards
      elsif @industry == "fashion_awards"
        Industry.find(2).awards
      elsif @industry == "film_awards"
        Industry.find(3).awards
      elsif @industry == 'music-awards'
        Industry.find(5).awards
      end 
    elsif params[:search_letter].present?
      @items = Award.where('name LIKE ?', "#{params[:search_letter]}%")
    else
      @arts = Industry.find(1).awards.last(10)
      @fashion = Industry.find(2).awards.last(10)
      @films = Industry.find(3).awards.last(10)
      @literatures = Industry.find(4).awards.last(10)
      @musics = Industry.find(5).awards.last(10)

      render 'awards_dashboard'
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @year = params[:year] || 1.year.ago.year
    @nominees = @award.nominees.where(rank_id: Rank.find_by_name('Winner').id).where(year: @year)
    @description = ActionView::Base.full_sanitizer.sanitize(@award.details).split(/\s+/).slice(0,300).join(' ');
    if policy(@award.business).update?
      @news_events_blogs = (@award.news_stories + @award.blogs + @award.events).sort_by(&:created_at).reverse
      @gallery_photos = @award.gallery_photos
    else
      @news_events_blogs = (@award.news_stories.viewable + @award.blogs.viewable + @award.events.viewable).sort_by(&:created_at).reverse
      @gallery_photos = @award.gallery_photos.viewable
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show_awards_categories
    @year = params[:year] || 1.year.ago.year
    @award_categories = @award.award_categories

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /awards/new
  def new
    @award = @parent.awards.build
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = @parent.awards.build(award_params)

    respond_to do |format|
      if @award.save
        format.html { redirect_to @award, notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        flash.now[:alert] = @award.errors.full_messages
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to @award, notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  def token_inputs
    render :json => Award.where('name ILIKE ?',"%#{params[:q]}%").as_json(only:[:id, :name])
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to awards_url, notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_award
      @award = Award.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :details, :image, :retained_image, :country, :start_year, :industry_id)
    end
end

app/views/awards/_alphabar.html.slim
ul.list-inline
  -('a'..'z').to_a.each do |letter|
    li
      h5.text-uppercase=link_to letter, awards_listings_path(params:{type: @type, search_letter: letter, locale: @locale}), class: letter == @search_letter ? 'active-link':''

  li
    h5.text-uppercase=link_to "all", awards_listings_path(params:{type: @type, locale: @locale}), class: @search_letter.blank? ? 'active-link':''

app/views/awards/_card.html.slim
=link_to media, class: 'linked-card' do
  .card.shadow
    .image-block
      =image_tag (media.image.nil? ? 'event.png' : media.image.url )
    .card-block
      /! Title
      .card-text.text-center= media.name
      .card-text.text-center= media.start_year
      .row
        .col-md-10.col-md-offset-1
          hr.title-underline

      .row.artist-info
        .col-md-8.no-gutters
          h5.no-margin-bottom.card-artist.card-title
          p.card-text

app/views/awards/_category-nominee-section.html.slim
  -@award_categories.each do |award_category|
    - unless award_category.nominees.where(year: @year).where('rank_id != ?', Rank.find_by_name('Unassigned').id).empty?
      h4= award_category.name
      .section-container.trending
        .row
          .col-md-12.margin-bottom-20
            - award_category.nominees.where(year: @year).where('rank_id != ?', Rank.find_by_name('Unassigned').id).sort_by{|nominee| nominee.rank_id}.each do |nominee|
              .col-md-4
                =link_to nominee.recipient, class: 'linked-list-item' do
                  .list-panel.border-right
                    .row
                      .col-md-3.no-gutters
                        =image_tag nominee_image(nominee.recipient).nil? ? 'default-profile-pic.png' : nominee_image(nominee.recipient), class: 'img-circle'
                      .col-md-6.no-gutters
                        .list-item-text-block.text-left
                          .h5.list-item-heading= nominee.award_category.name
                          .list-item-text= nominee.name
                          .list-item-text= nominee.rank.name
                          .list-item-text= @year
        hr.hr

app/views/awards/_form.html.slim
= simple_form_for([@parent,@award]) do |f|
  .row
    .col-md-3
      .image#image-box.box-border.editable
        .edit-overlay
          i.fi-camera
          ' &nbsp; update profile picture
          = f.input :image, as: :file, label: '&nbsp;'.html_safe
          = f.input :retained_image, as: :hidden
        =image_tag (@award.image_stored? ? @award.image.url : 'default-award-pic.png'), id: 'profile-pic'

    .col-md-9
      .form-inputs
        .form-group
          .row
            .col-md-9
              = f.input :name, label: false, placeholder: 'Award Name', input_html:{class: 'form-control'}
            .col-md-3
              = f.input :start_year, label: false, placeholder: 'Start Year', input_html:{class: 'form-control'}
        .form-group
          .row
            .col-md-12
              = f.input :details, label: false, placeholder: 'About the award.....', input_html:{class: 'form-control'}
        .form-group
          .row
            .col-md-6
              = f.input :country, label: false, prompt: 'Select a Country', input_html:{class: 'form-control'}

            .col-md-6
              = f.association :industry, label: false, prompt: 'Select an Industry', input_html:{class: 'form-control'}

      .form-actions
        = f.button :submit, class: 'btn site-btn-primary pull-right'

app/views/awards/_gallery_photos.html.slim
.col-md-12
  .row#lightgallery
    - @gallery_photos.each do |gallery_photo|
      =link_to gallery_photo.image.url, class: 'col-md-1-5' do
        =image_tag gallery_photo.image.url

app/views/awards/_nominee-section.html.slim
- @nominees.each do |nominee|
  .col-md-4
    =link_to nominee.recipient, class: 'linked-list-item' do
      .list-panel.border-right
        .row
          .col-md-3.no-gutters
            =image_tag nominee_image(nominee.recipient).nil? ? 'default-profile-pic.png' : nominee_image(nominee.recipient), class: 'img-circle'
          .col-md-6.no-gutters
            .list-item-text-block.text-left
              .h5.list-item-heading= nominee.award_category.name
              .list-item-text= nominee.name
              .list-item-text= nominee.rank.name
              .list-item-text= @year

app/views/awards/awards_dashboard.html.slim
.section-container.specialities.margin-bottom-20
  .row
    .col-md-12
      h3.text-capitalize.no-margin-top Awards
      #locale-links #{link_to 'local', request.path, class: @locale == 'local' ? 'active-link':'' } | #{link_to 'international', request.path + '?locale=international', class: @locale == 'international' ? 'active-link':''}
  .row
    .col-md-12.text-center.alphabar
      =render partial: 'alphabar'
  .row
    .col-md-12.text-center
      - if @category_count.present?
        - @category_count.each do |key, count|
          - if(count > 0)
            = link_to awards_listings_path({type: key, industry: key, locale: @locale})
              .col-md-2.speciality-box
                =image_tag "/images/#{key.downcase.gsub(',','').gsub(' ', '_')}.jpg"
                .image-text
                   strong #{key.capitalize} (#{count})
  .row
    - if !@arts.empty?
      .col-md-12
        h3 Arts
        - @arts.each do |art|
          .col-md-1-5
              =render partial: 'card', locals: {media: art}
    - if !@fashion.empty?
     .col-md-12
      h3 Fashion
      - @fashion.each do |fashion|
        .col-md-1-5
            =render partial: 'card', locals: {media: fashion}
    - if !@films.empty?
     .col-md-12
      h3 Films
      - @films.each do |film|
        .col-md-1-5
            =render partial: 'card', locals: {media: film}
    - if !@literatures.empty?
     .col-md-12
      h3 Literature
      - @litratures.each do |litrature|
        .col-md-1-5
            =render partial: 'card', locals: {media: litrature}
    - if !@musics.empty?
     .col-md-12
      h3 Music
      - @musics.each do |music|
        .col-md-1-5
            =render partial: 'card', locals: {media: music}
javascript:
  if($('.speciality-box').length ==0){
    $('.speciality-hr').hide();
  }

app/views/awards/awards_listings.html.slim
.section-container.specialities.margin-bottom-20
  .row
    .col-md-12
      h3.text-capitalize.no-margin-top Awards | #{@industry}
      #locale-links #{link_to 'local', request.path, class: @locale == 'local' ? 'active-link':'' } | #{link_to 'international', request.path + '?locale=international', class: @locale == 'international' ? 'active-link':''}
  .row
    .col-md-12.text-center.alphabar
      =render partial: 'alphabar'
  - if @industry == 'gallery'
    - if @items.present?
      - @items.each do |gallery|
        .col-md-3
            =render partial: 'gallery', locals: {media: gallery}
  - else
    .col-md-12
      - if @items.present?
        - @items.each do |result|
          .row.border-bottom.padding-bottom-20.business-listing
            .col-md-2.business-logo
              =link_to result do
                =image_tag entity_image(result)
            .col-md-7.border-right
              .row
                .col-md-10
                    h4= link_to result.name, result
              .row
               - if @industry != 'gallery'
                - if @industry == 'stories'
                  .col-md-12= truncate_html(result.name.html_safe, length: 150, omission: "#{link_to '...(continued)', result}")
                - elsif @industry == 'books' || 'productions'
                  .col-md-12= truncate_html(result.name.html_safe, length: 150, omission: "#{link_to '...(continued)', result}")
                - else
                  .col-md-12= truncate_html(result.description.html_safe, length: 150, omission: "#{link_to '...(continued)', result}")
            .col-md-3.business-details
              .row
                .col-md-12
                  .example
                    strong Country:&nbsp;
                    = result.country
                  .example
                    strong Industry:&nbsp;
                      #{@industry}
                  .example
                    strong Type:&nbsp;
                    = result.class.name

app/views/awards/edit.html.slim
.section-container
  .row
    .col-md-12
      h3 Edit Award
  == render 'form'

app/views/awards/index.html.slim
h1 Listing awards

table
  thead
    tr
      th Name
      th Business
      th Details
      th Image uid
      th Country
      th Start year
      th Industry
      th
      th
      th

  tbody
    - @awards.each do |award|
      tr
        td = award.name
        td = award.business_id
        td = award.details
        td = award.image_uid
        td = award.country
        td = award.start_year
        td = award.industry_id
        td = link_to 'Show', award
        td = link_to 'Edit', edit_award_path(award)
        td = link_to 'Destroy', award, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Award', new_award_path

app/views/awards/new.html.slim
.section-container
  .row
    .col-md-12
      h3 New Award
  == render 'form'

app/views/awards/show.html.slim
=title @award.name
.section-container
  .row.profile-details.margin-bottom-20.margin
    .col-md-3
      -if policy(@award.business).update?
        .pro-image#image-box.box-border.editable
          =simple_form_for @award do |f|
            .edit-overlay
              i.fi-camera
              ' &nbsp; update award image
              = f.input :image, as: :file, label: '&nbsp;'.html_safe
              = f.input :retained_image, as: :hidden
            =f.submit 'Save Image', id: 'save-btn', class:'button btn site-btn-primary'
          =image_tag (@award.image_stored? ? @award.image.url : 'default-award-pic.png'), id: 'profile-pic'
      -else
        .pro-image
          =image_tag (@award.image_stored? ? @award.image.url : 'default-award-pic.png'), id: 'profile-pic'

    .col-md-9
      .row
        h3.no-margin-top.text-uppercase.text-primary= @award.name
      .row
        .col-md-12.no-gutters
          b Country:&nbsp;
          = ISO3166::Country.find_country_by_alpha2(@award.country).name
      .row
        .col-md-12.no-gutters
          b Industry:&nbsp;
          = @award.industry.name
      .row
        .col-md-12.no-gutters
          = @award.details.html_safe if @award.details
      .row
        .col-md-1.col-md-offset-11.no-gutters
          =link_to 'Edit', edit_award_path(@award) if policy(@award.business).update?
      -if policy(@award.business).update?
        .row
          .col-md-12
            h4=link_to 'Add/Edit Award Categories', award_categories_path(@award), class: 'btn site-btn-primary'

.section-container
  hr.hr
  .row
    .col-md-12.text-center.prof-nav
      ul.list-inline
        li
          h4
            = link_to 'Winners', award_path(@award), class: 'active-link'
        li
          h4
            =link_to 'Categories', show_awards_categories_award_path(@award)

  hr.hr

.section-container
  .row
    .col-md-12.text-center.prof-nav
      ul.list-inline#years
        - (@award.start_year..Date.today.year).to_a.reverse[0..5].each do |year|
          li
            h5.no-top-margin= link_to year, award_path(@award, params:{year: year}), class: year == @year ? "active-link" : "", remote: true
  hr.hr

.award-winners-section.trending.margin-top-20
  .section-container
    .row
      .col-md-12.margin-bottom-20#nominee-section
        = render 'nominee-section'

    hr.hr

-if policy(@award.business).update? || !@news_events_blogs.empty?
  .artist-news-blogs-and-events-section
    .section-container#news-events
      .row
        .col-md-12
          h4 NEWS, BLOGS AND EVENTS
      .row
        .col-md-12
          .row#news-events-blogs-cards
            - @news_events_blogs.each do |card|
              .col-md-4.reduced-padding[id = "#{card.class.name.downcase}-#{card.id}"]
                =render partial: 'artists/news-event-blog-card', locals:{card: card}

      hr.hr

-if policy(@award.business).update? || !@award.gallery_photos.empty?
  .featured-section
    .section-container
      .row
        .col-md-12
          h3 GALLERY
      - if policy(@award.business).update?
        .row
          .col-md-12
            #progress
              .bar style=("width: 0%;")
            =simple_form_for([@award,GalleryPhoto.new]) do |f|
              = f.input :image, as: :file, label: false, input_html:{multiple: true, name: 'gallery_photo[image]', class: 'input-1'}

      #award-gallery-photos.row
        =render partial: 'gallery_photos', locals:{award: @award}

app/views/awards/show.js.erb
$('#years a').removeClass('active-link')
$('#years a:contains("<%= @year %>")').addClass('active-link')

$('#nominee-section').html("<%= escape_javascript render 'nominee-section' %>")

app/views/awards/show_awards_categories.js.erb
$('#years a').removeClass('active-link')
$('#years a:contains("<%= @year %>")').addClass('active-link')
$('#nominee-section').html("<%= escape_javascript render 'category-nominee-section' %>")